### ISSUE TITLE
SegmentTemplate substitution parameters

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/DASH-IF-Conformance#357]
Conformance check to support clarification on the SegmentTemplate substitution parameters in clause 4.3.2.2.8

**Comment by niteeshbhat** [comment]
The above clause clarifies that only %0[width]d is permitted in the SegmentTemplate substitution while calculating segment URLs.
For conformance software, the DASH submodule has SegmentURLs.php which covers this check.
Also in the live conformance tool, this is supported, from the commit https://github.com/Dash-Industry-Forum/Conformance-and-reference-source/tree/f7e7d8ba5152ef8062d0c97bcb781eb3ad61db04

Hence closing the issue here.
Reopen if any issue observed.
