### ISSUE TITLE
Visitor log file gets deleted

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-Conformance#451]

**Comment by eceozturk** [comment]
This issue is fixed by modifying the server syncing script. Closing this issue now.

**Comment by eceozturk** [comment]
The deletion of the file is associated with visitors simultaneously accessing the same single file for logging respective information. Instead of writing into a single log file, for each user an individual visitor log file is created in "visitorLogs" folder. The content in this folder can then be used for post processing at any time (outside of the usual conformance testing) by using a script. 

The related PR #461 

The code is deployed on server and the script (which is not in the github code) is placed in the server.

**Comment by waqarz** [comment]
We shd add the script to code as well.
