### ISSUE TITLE
Hangs on 4th AdapatationSet of MPEG's CMAF conformance stream

### ISSUE THREAD

**Issue by boy-vd** [Dash-Industry-Forum/DASH-IF-Conformance#476]
When trying to get results from the validator using a mirror of MPEG's conformance stream for CMAF, the DASH-IF conformance tool doesn't progress beyond the 4th AdaptationSet. I have tested and reproduced this behavior multiple times. When the conformance tool reaches the 4th AdaptationSet, it gets stuck immediately at '5 KB downloaded' and '0 MB processed':

`Processing Representation 1 in Adaptationset 4 in Period 1, 25% done ( 5 KB downloaded, 0 MB processed )`

The stream I'm trying to validate is the following (a mirror of MPEG's CMAF conformance stream): https://usp-cmaf-test.s3.eu-central-1.amazonaws.com/tears-of-steel.mpd

It seems like the PHP script gets stuck in some kind of loop, as my browser keeps requesting 'progress.xml' (most often with, and sometimes without a query parameter that seems to represent current time):

`https://conformance.dashif.org/conformance/current/Conformance-Frontend/temp/id8314607669/progress.xml`

**Comment by eceozturk** [comment]
Thank you for reporting this issue. As you have suspected, PHP side script was getting stuck in an infinite loop due to a missing condition check. I provided a fix for this, merged into this repository and deployed on the server accessible at (https://conformance.dashif.org/). 

Closing this issue now. Please reopen if the issue persists.
