### ISSUE TITLE
Unclear error on video tracks of MPEG's CMAF conformance stream

### ISSUE THREAD

**Issue by boy-vd** [Dash-Industry-Forum/DASH-IF-Conformance#479]
First off, thanks for the very quick fix on #476! I can now run the validator on the MPEG conformance stream for CMAF without it hanging (link: https://usp-cmaf-test.s3.eu-central-1.amazonaws.com/tears-of-steel.mpd).

However, a few errors get reported that I don't really understand (one other I reported in #480).

**My question is whether this is the validator misreporting an error because it cannot parse something that it should be able to parse, or whether there is actually something wrong with track?**

For the video tracks, the error that is unclear is shown below. It is the same for all the video tracks:
```
### error: moov-1:trak-1:mdia-1:minf-1:stbl-1:stsd-1 
### Validate_AVCConfigRecord: Not enough bits left in the bitstream for further attribute validation
```

However, when I use [MP4Box.js](https://gpac.github.io/mp4box.js/test/filereader.html) it seems to be able to read the `avcC` box just fine (see below). Also, playback of the stream in DASH.js 3.0 doesn't produce any problems.

Information from one of the video tracks (https://usp-cmaf-test.s3.eu-central-1.amazonaws.com/tears-of-steel-avc1-1500k.cmfv) taken from `MP4Box.js`:

`moov` > `trak` > `mdia` > `minf` > `stbl` > `stsd`
```
type                  stsd
size                  176
flags                 0
version               0
start                 442
```
`stsd` > `avc1`
```
type                  avc1
size                  160
start                 458
data_reference_index  1
width                 1680
height                750
horizresolution       4718592
vertresolution        4718592
frame_count           1
compressorname        AVC Coding
depth                 24
```
`stsd` > `avc1` > `avcC`
```
type                  avcC
size                  54
start                 544
configurationVersion  1
AVCProfileIndication  100
profile_compatibility 0
AVCLevelIndication    40  
lengthSizeMinusOne    3
nb_SPS_nalus          1
SPS                   [object Object]
nb_PPS_nalus          1
PPS                   [object Object]
```
`stsd` > `avc1` > `btrt`
```
type                  btrt
size                  20
start                 598
data                  00000000 035cb470 0016e748
bufferSizeDB          0
maxBitrate            56407152
avgBitrate            1501000
```

If you need more info, please let me know :-)!

**Comment by eceozturk** [comment]
This seems to be a valid error from the validator side. 

**As a general information:** The AVCConfigRecord for specific profiles (namely 100, 110, 122 and 144 (and I think there is a new addition to this in the newer version)) requires additional information to be present after SPS and PPS. This information is regarding some reserved bits, chroma format, bit depth, SPS Extension (optional).

**Testing result:** I have debugged a bit with the available content given at the link you provided in this issue. For this specific test vector, the profile of the video content (Adaptation Set 12, Representation 3) is 100; and thus, the additional information provided above is checked for its presence. However, the bits left at this point seems to be 0.

So, it should be an encoder error due to missing bits. 

I am closing this issue now. Please reopen if any more information is needed for this :)
