### ISSUE TITLE
unable to view failure reasons

### ISSUE THREAD

**Issue by HunterLarco** [Dash-Industry-Forum/DASH-IF-Conformance#486]
# Steps to reproduce

1. Go to https://conformance.dashif.org/
2. Use manifest https://storage.googleapis.com/sadboi-media/maninthewoods/manifest.mpd

# Expected result

Failures are explained.

# Observed result

[Failures are present](https://user-images.githubusercontent.com/2695807/71132594-f15e8980-21c5-11ea-8444-825d8964c8c9.png) with no explanation. Clicking on the logs for failures results in [404 errors](https://user-images.githubusercontent.com/2695807/71132607-fa4f5b00-21c5-11ea-9171-c993a751945e.png).

**Comment by eceozturk** [comment]
This problem occurs because there is no initialization and media segment(s) in the signaled location by the MPD. 

From the below image, the location is computed e.g. for the first appearing representation as:
https://storage.googleapis.com/sadboi-media/maninthewoods/manifest.mpd/v480
This location does not have any segment to be downloaded and consequently to be validated. Therefore, the does not exists any log file to be generated which results in the 404 message.

![image](https://user-images.githubusercontent.com/35132231/71159915-6ef0bc80-21fb-11ea-830f-f7ebf1df00e9.png)

This can be solved by modifying the BaseURLs in the MPD such that they point to correct locations.

From our side, we actually provide information on missing links (not found segment URLs), however I guess this was overwritten by some commits. I opened an issue for this [here](#487).

**Comment by HunterLarco** [comment]
I've resolved the misconfigured BaseURL and still experience the same issue.

See https://storage.googleapis.com/sadboi-media/maninthewoods/manifest.mpd for the manifest.

EG: https://storage.googleapis.com/sadboi-media/maninthewoods/v480/1.m4s exists

**Comment by eceozturk** [comment]
The mentioned URL (https://storage.googleapis.com/sadboi-media/maninthewoods/**v480/1.m4s**) exists; however, the computed URL is https://storage.googleapis.com/sadboi-media/maninthewoods/**v480/v480/1.m4s** due to SegmentTemplate@media. 

This can be fixed by either removing the BaseURL element within the Representation element or by removing "v480" from the SegmentTemplate@media attribute. This would also apply to other Representations and AdaptationSets.

Additionally, computed URL for SegmentTemplate@initialization (https://storage.googleapis.com/sadboi-media/maninthewoods/v480/manifest_set1_init.mp4) does not seem to exist.

**Comment by waqarz** [comment]
Tracked here: https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/487
