### ISSUE TITLE
The MPD contains an attribute that is not part of the HbbTV profile', i.e., found 'subsegmentAlignment' as true

### ISSUE THREAD

**Issue by jpiesing** [Dash-Industry-Forum/DASH-IF-Conformance#489]
I have an MPD which isn't behaving as expected. When I analyse it with enforce profiles set to "DVB", I get a number of schematron errors (see below). 

The error message says subsegmentAlignment and subsegmentStartsWithSAP are not part of the HbbTV profile but I'm not checking against the HbbTV profile but against the DVB one. Which profile is it actually checking against?

If it's checking against the DVB profile in spite of the error message then this is wrong. DVB-DASH 4.2.7 says "If an AdaptationSet element contains more than one Representation element, then this AdaptationSet element can be ignored unless AdaptationSet@subsegmentAlignment is present and has value of 'true' and AdaptationSet@subsegmentStartsWithSAP is present and has value of 1 or 2."

The MPD URL is available by email on request.

 location="/*:MPD[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:Period[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:AdaptationSet[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]">

HbbTV-DVB DASH Validation Requirements check violated for HbbTV: Section 'MPD' - The MPD contains an attribute that is not part of the HbbTV profile', i.e., found 'subsegmentAlignment' as true

location="/*:MPD[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:Period[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:AdaptationSet[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]">

HbbTV-DVB DASH Validation Requirements check violated for HbbTV: Section 'MPD' - The MPD contains an attribute that is not part of the HbbTV profile', i.e., found 'subsegmentStartsWithSAP' as 1 or 2

location="/*:MPD[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:Period[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:AdaptationSet[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][2]">

HbbTV-DVB DASH Validation Requirements check violated for HbbTV: Section 'MPD' - The MPD contains an attribute that is not part of the HbbTV profile', i.e., found 'subsegmentAlignment' as true

location="/*:MPD[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:Period[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:AdaptationSet[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][2]">

HbbTV-DVB DASH Validation Requirements check violated for HbbTV: Section 'MPD' - The MPD contains an attribute that is not part of the HbbTV profile', i.e., found 'subsegmentStartsWithSAP' as 1 or 2

Schematron validation not successful - DASH is not valid!

**Comment by jpiesing** [comment]
Looking at this more closely, the MPD says it's an HbbTV profile one but still, I would expect a warning if I ask for an MPD to be checked against a different profile than the one declared in MPD@profiles.

Also it's not obvious to me why subsegmentAlignment is not part of the HbbTV profile. I know in DASH-IF that subsegmentAlignment and subsegmentStartsWithSAP are most commonly used with the MPEG DASH on demand profile but I've not yet found anything prohibiting its use with the MPEG DASH live profile.

**Comment by eceozturk** [comment]
Thank you for reporting this issue. I have provided some information on the tool and analysis on the error below. Please let me know if this clarifies it. For further details, I could ask for the MPD URL via e-mail.

About the profiles that the HbbTV and DVB-DASH validation tool uses:

- The validation is done against both for the profiles in MPD@profiles and the profiles that are enforced from the settings/gear icon from the top right corner. Therefore, the conformance test in this case was run for both HbbTV and DVB profiles (This is why the the error logs for HbbTV profile is also given in the reports).
- The profiles used for the validation are actually reported on the user interface (see Figure 1). However I have noticed that this information is provided only when "MPD conformance only" field is not checked. If this is checked, the information is not shown on the user interface (see Figure 2). So, this could be the reason why there was no warning/information to be seen by the user. 
    - For this I opened an issue that can be tracked [here](https://github.com/Dash-Industry-Forum/Conformance-Frontend/issues/71).

![profiles](https://user-images.githubusercontent.com/35132231/72785476-a0f6a380-3c2b-11ea-87ef-4efef6bd86ec.png)
Figure 1: Profile information provided

![profiles1](https://user-images.githubusercontent.com/35132231/72785507-ace26580-3c2b-11ea-853b-d52c74eaa25c.png)
Figure 2: Profile information not provided when MPD conformance only

About the error log:

- One of the requirements in HbbTV and DVB-DASH validation tool was to report errors if the MPD includes an element in a Representation or AdaptationSet that is declared with the profile being validated against but the MPD element is not part of that profile. Since HbbTV profile is for live services and that subsegmentAlignment and subsegmentStartsWithSAP are for DASH on demand services, this error is reported.
- The mentioned error is given only for the HbbTV profile contained in the MPD@profiles: 
"HbbTV-DVB DASH Validation Requirements check violated for **HbbTV**"
Therefore, DVB's inclusion of these parameters actually does not change the result.

**Comment by dsilhavy** [comment]
Closing this, please comment is this should be reopened
