### ISSUE TITLE
Invalid MPD test vector: Timecode Axinom DRM HEVC, MultiRes, MultiRate 25fps

### ISSUE THREAD

**Issue by emarsden** [Dash-Industry-Forum/DASH-IF-Conformance#681]
The DASH manifest at 

   https://dash.akamaized.net/dash264/TestAdvertising/DRM/Axinom-DRM-in-disconnected-environments_HEVC_MultiRes_MultiRate_25fps.mpd

which is [listed](https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/blob/8855681063b958ae1c5ff00707265c36290890f6/functional-tests/dashif/dashjs.json#L942) in your conformance tests is invalid. Line 29 of the MPD is

      <BaseURL../../TestCasesIOP33/Content/audio/mp4a/</BaseURL>

(missing ">"). This does not appear to be voluntary.

**Comment by dsilhavy** [comment]
@rbouqueau Do you have access to the Akamai CDN and can fix this?

**Comment by rbouqueau** [comment]
I do. I checked randomly some other files in the folder and they seem fine. So I assume this was a typo.

I fixed it on the server. However due to the caching policy of the server it may take quite some time to propagate. If that's not workable, an alternative would be to make a copy and change all links to that reference.

**Comment by dsilhavy** [comment]
Thanks @rbouqueau

**Comment by rbouqueau** [comment]
Fixed. Closing.
